<a href="https://colab.research.google.com/github/Nakul-Narang/Ai_agent/blob/main/Iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import sklearn
import pandas as pd
import numpy as np
Dataset=pd.read_csv("/content/IRIS.csv")

In [41]:
x=Dataset
x.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [42]:
print (x.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [43]:
X1=x.drop('species',axis=1)
X1.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [44]:
Y=x['species']

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X1,Y,test_size=0.2,random_state=42)
print (X_train.shape)
print (X_test.shape)

(120, 4)
(30, 4)


In [46]:
from sklearn.linear_model import LogisticRegression

# Initialize the model
log_reg = LogisticRegression(max_iter=200)

# Train the model
log_reg.fit(X_train, Y_train)

# Predict on test data
y_pred = log_reg.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Train different models
dt = DecisionTreeClassifier().fit(X_train, Y_train)
rf = RandomForestClassifier().fit(X_train, Y_train)
svm = SVC().fit(X_train, Y_train)

# Predictions
y_pred_dt = dt.predict(X_test)
y_pred_rf = rf.predict(X_test)
y_pred_svm = svm.predict(X_test)

# Compare accuracies
print("Decision Tree Accuracy:", accuracy_score(Y_test, y_pred_dt))
print("Random Forest Accuracy:", accuracy_score(Y_test, y_pred_rf))
print("SVM Accuracy:", accuracy_score(Y_test, y_pred_svm))

Decision Tree Accuracy: 1.0
Random Forest Accuracy: 1.0
SVM Accuracy: 1.0


In [49]:
print("🌸 Iris Flower Prediction 🌸")
sepal_length = float(input("Enter Sepal Length (cm): "))
sepal_width  = float(input("Enter Sepal Width (cm): "))
petal_length = float(input("Enter Petal Length (cm): "))
petal_width  = float(input("Enter Petal Width (cm): "))

# Convert input into dataframe with correct column names
sample = pd.DataFrame([[sepal_length, sepal_width, petal_length, petal_width]],
                      columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])

# Predict using the trained model
prediction = log_reg.predict(sample)
print("\n✅ Predicted Species:", prediction[0])

🌸 Iris Flower Prediction 🌸
Enter Sepal Length (cm): 45
Enter Sepal Width (cm): 45
Enter Petal Length (cm): 45
Enter Petal Width (cm): 45

✅ Predicted Species: Iris-virginica
